[package]
name = "webpki-root-certs"
version = "0.26.11"
license = "CDLA-Permissive-2.0"
description = "Override of webpki-root-certs that does not embed anything"

[dependencies]
pki-types = { package = "rustls-pki-types", version = "1.8", default-features = false }
