name: Publish

permissions:
  contents: write

on:
  release:
    types: [published]

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    if: github.repository_owner == 'nikarh'
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
        if: "!contains(matrix.target, 'aarch64')"
      - uses: taiki-e/install-action@cross
        if: contains(matrix.target, 'aarch64')
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ github.event.repository.name }}
          include: LICENSE-MIT,LICENSE-APACHE,CHANGELOG.md,README.md
          target: ${{ matrix.target }}
          tar: all
          archive: ${{ github.event.repository.name }}-$target-$tag
          token: ${{ secrets.GITHUB_TOKEN }}
